# Generated by Django 3.2 on 2021-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('topnews', models.BooleanField()),
                ('business', models.BooleanField()),
                ('technology', models.BooleanField()),
                ('entertainment', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('science', models.BooleanField()),
                ('health', models.BooleanField()),
            ],
        ),
    ]
