# Generated by Django 3.2 on 2021-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='alternate_contact',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='contact',
            field=models.IntegerField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
