# Generated by Django 3.2 on 2021-10-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
