# Generated by Django 3.2 on 2021-10-22 11:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('top', 'TOP'), ('tech', 'TECH'), ('economy', 'ECONOMY'), ('sports', 'SPORTS'), ('politics', 'POLITICS'), ('lifenhealth', 'LIFESTYLE & HEALTH'), ('entertainment', 'ENTERTAINMENT')], default='top', max_length=58),
            preserve_default=False,
        ),
    ]
